-- =====================================================================
-- 娴嬭瘯鏁版嵁鍒濆鍖栬剼鏈?(SQLite)
-- 鍖呭惈: 3涓竴绾ч儴闂?+ 10涓簩绾ч儴闂?+ 20涓笁绾ч儴闂?+ 姣忛儴闂?涓敤鎴?姘存祾浼犱汉鐗?
-- 浣跨敤鍥哄畾ID閬垮厤鍐茬獊: 閮ㄩ棬 100-139, 鐢ㄦ埛 100-264
-- 骞傜瓑璁捐: 閫氳繃 NOT EXISTS 鍒ゆ柇閬垮厤閲嶅鎻掑叆
-- =====================================================================

-- ==================== 涓€绾ч儴闂?(3涓? ====================
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 100, 0, '鎬荤粡鍔?, 'DEPT-ZJB', 'company', 1, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 100);

INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 101, 0, '鎶€鏈爺鍙戜腑蹇?, 'DEPT-JSZX', 'center', 2, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 101);

INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 102, 0, '杩愯惀绠＄悊閮?, 'DEPT-YYGL', 'center', 3, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 102);

-- ==================== 浜岀骇閮ㄩ棬 (10涓? ====================
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 110, 100, '鎴樼暐鍙戝睍閮?, 'DEPT-ZLFZ', 'dept', 1, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 110);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 111, 100, '浜哄姏璧勬簮閮?, 'DEPT-RLZY', 'dept', 2, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 111);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 112, 101, '骞冲彴鏋舵瀯閮?, 'DEPT-PTJG', 'dept', 1, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 112);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 113, 101, '搴旂敤寮€鍙戦儴', 'DEPT-YYKF', 'dept', 2, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 113);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 114, 101, '璐ㄩ噺淇濋殰閮?, 'DEPT-ZLBZ', 'dept', 3, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 114);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 115, 102, '甯傚満钀ラ攢閮?, 'DEPT-SCYX', 'dept', 1, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 115);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 116, 102, '瀹㈡埛鏈嶅姟閮?, 'DEPT-KHFW', 'dept', 2, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 116);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 117, 102, '渚涘簲閾鹃儴', 'DEPT-GYL', 'dept', 3, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 117);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 118, 102, '璐㈠姟绠＄悊閮?, 'DEPT-CWGL', 'dept', 4, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 118);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time)
SELECT 119, 102, '琛屾斂绠＄悊閮?, 'DEPT-XZGL', 'dept', 5, 1, datetime('now'), datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 119);

-- ==================== 涓夌骇閮ㄩ棬 (20涓? ====================
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 120, 110, '甯傚満鎴樼暐缁?, 'DEPT-SCZL', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 120);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 121, 110, '鎶曡祫鍒嗘瀽缁?, 'DEPT-TZFX', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 121);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 122, 111, '鎷涜仒鍩硅缁?, 'DEPT-ZPPX', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 122);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 123, 111, '钖叕缁╂晥缁?, 'DEPT-XCJX', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 123);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 124, 112, '鍩虹鏋舵瀯缁?, 'DEPT-JCJG', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 124);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 125, 112, '鏁版嵁骞冲彴缁?, 'DEPT-SJPT', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 125);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 126, 113, '鍓嶇寮€鍙戠粍', 'DEPT-QDKF', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 126);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 127, 113, '鍚庣寮€鍙戠粍', 'DEPT-HDKF', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 127);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 128, 114, '娴嬭瘯宸ョ▼缁?, 'DEPT-CSGC', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 128);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 129, 114, '瀹夊叏瀹¤缁?, 'DEPT-AQSJ', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 129);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 130, 115, '鍝佺墝鎺ㄥ箍缁?, 'DEPT-PPTG', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 130);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 131, 115, '娓犻亾杩愯惀缁?, 'DEPT-QDYY', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 131);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 132, 116, '鍞墠鍜ㄨ缁?, 'DEPT-SQZX', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 132);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 133, 116, '鍞悗鏀寔缁?, 'DEPT-SHZC', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 133);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 134, 117, '閲囪喘绠＄悊缁?, 'DEPT-CGGL', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 134);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 135, 117, '浠撳偍鐗╂祦缁?, 'DEPT-CCWL', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 135);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 136, 118, '浼氳鏍哥畻缁?, 'DEPT-KJHS', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 136);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 137, 118, '璧勯噾绠＄悊缁?, 'DEPT-ZJGL', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 137);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 138, 119, '鍚庡嫟淇濋殰缁?, 'DEPT-HQBZ', 'group', 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 138);
INSERT INTO sys_dept (id, parent_id, dept_name, dept_code, dept_type, sort_order, status, create_time, update_time) SELECT 139, 119, '浼佷笟鏂囧寲缁?, 'DEPT-QYWH', 'group', 2, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE id = 139);

-- ==================== 鐢ㄦ埛鏁版嵁 (姣忛儴闂?浜? 姘存祾浼犱汉鐗? ====================
-- 閮ㄩ棬100: 鎬荤粡鍔?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 100, 'songjiang', '123456', '瀹嬫睙', 100, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 100);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 101, 'lujunyi', '123456', '鍗繆涔?, 100, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 101);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 102, 'wuyong', '123456', '鍚寸敤', 100, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 102);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 103, 'gongsunsheng', '123456', '鍏瓩鑳?, 100, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 103);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 104, 'guansheng', '123456', '鍏宠儨', 100, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 104);
-- 閮ㄩ棬101: 鎶€鏈爺鍙戜腑蹇?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 105, 'linchong', '123456', '鏋楀啿', 101, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 105);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 106, 'qinming', '123456', '绉︽槑', 101, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 106);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 107, 'huyanzhuo', '123456', '鍛煎欢鐏?, 101, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 107);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 108, 'huarong', '123456', '鑺辫崳', 101, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 108);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 109, 'chaijin', '123456', '鏌磋繘', 101, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 109);
-- 閮ㄩ棬102: 杩愯惀绠＄悊閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 110, 'liying', '123456', '鏉庡簲', 102, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 110);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 111, 'zhutong', '123456', '鏈变粷', 102, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 111);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 112, 'luzhishen', '123456', '椴佹櫤娣?, 102, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 112);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 113, 'wusong', '123456', '姝︽澗', 102, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 113);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 114, 'dongping', '123456', '钁ｅ钩', 102, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 114);
-- 閮ㄩ棬110: 鎴樼暐鍙戝睍閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 115, 'zhangqing', '123456', '寮犳竻', 110, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 115);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 116, 'yangzhi', '123456', '鏉ㄥ織', 110, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 116);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 117, 'xuning', '123456', '寰愬畞', 110, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 117);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 118, 'suochao', '123456', '绱㈣秴', 110, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 118);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 119, 'daizong', '123456', '鎴村畻', 110, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 119);
-- 閮ㄩ棬111: 浜哄姏璧勬簮閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 120, 'liutang', '123456', '鍒樺攼', 111, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 120);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 121, 'likui', '123456', '鏉庨€?, 111, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 121);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 122, 'shijin', '123456', '鍙茶繘', 111, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 122);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 123, 'muhong', '123456', '绌嗗紭', 111, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 123);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 124, 'leiheng', '123456', '闆锋í', 111, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 124);
-- 閮ㄩ棬112: 骞冲彴鏋舵瀯閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 125, 'lijun', '123456', '鏉庝繆', 112, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 125);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 126, 'ruanxiaoer', '123456', '闃皬浜?, 112, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 126);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 127, 'zhangheng', '123456', '寮犳í', 112, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 127);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 128, 'ruanxiaowu', '123456', '闃皬浜?, 112, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 128);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 129, 'zhangshun', '123456', '寮犻『', 112, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 129);
-- 閮ㄩ棬113: 搴旂敤寮€鍙戦儴
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 130, 'ruanxiaoqi', '123456', '闃皬涓?, 113, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 130);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 131, 'yangxiong', '123456', '鏉ㄩ泟', 113, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 131);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 132, 'shixiu', '123456', '鐭崇', 113, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 132);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 133, 'xiezhen', '123456', '瑙ｇ弽', 113, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 133);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 134, 'xiebao', '123456', '瑙ｅ疂', 113, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 134);
-- 閮ㄩ棬114: 璐ㄩ噺淇濋殰閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 135, 'yanqing', '123456', '鐕曢潚', 114, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 135);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 136, 'huangxin', '123456', '榛勪俊', 114, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 136);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 137, 'sunli', '123456', '瀛欑珛', 114, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 137);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 138, 'xuanzan', '123456', '瀹ｈ禐', 114, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 138);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 139, 'haosiwen', '123456', '閮濇€濇枃', 114, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 139);
-- 閮ㄩ棬115: 甯傚満钀ラ攢閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 140, 'hantao', '123456', '闊╂粩', 115, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 140);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 141, 'pengqi', '123456', '褰帢', 115, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 141);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 142, 'shantinggui', '123456', '鍗曞环鐝?, 115, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 142);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 143, 'weidingguo', '123456', '榄忓畾鍥?, 115, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 143);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 144, 'xiaorang', '123456', '钀ц', 115, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 144);
-- 閮ㄩ棬116: 瀹㈡埛鏈嶅姟閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 145, 'peixuan', '123456', '瑁村', 116, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 145);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 146, 'oupeng', '123456', '娆ч箯', 116, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 146);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 147, 'dengfei', '123456', '閭撻', 116, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 147);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 148, 'yanshun', '123456', '鐕曢『', 116, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 148);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 149, 'yanglin', '123456', '鏉ㄦ灄', 116, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 149);
-- 閮ㄩ棬117: 渚涘簲閾鹃儴
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 150, 'lingzhen', '123456', '鍑屾尟', 117, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 150);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 151, 'jiangjing', '123456', '钂嬫暚', 117, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 151);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 152, 'lvfang', '123456', '鍚曟柟', 117, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 152);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 153, 'guosheng', '123456', '閮洓', 117, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 153);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 154, 'andaoquan', '123456', '瀹夐亾鍏?, 117, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 154);
-- 閮ㄩ棬118: 璐㈠姟绠＄悊閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 155, 'huangfuduan', '123456', '鐨囩敨绔?, 118, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 155);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 156, 'wangdingliu', '123456', '鐜嬪畾鍏?, 118, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 156);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 157, 'yubaosi', '123456', '閮佷繚鍥?, 118, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 157);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 158, 'duanqi', '123456', '娈电惇', 118, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 158);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 159, 'baixiuying', '123456', '鐧界鑻?, 118, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 159);
-- 閮ㄩ棬119: 琛屾斂绠＄悊閮?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 160, 'songwan', '123456', '瀹嬩竾', 119, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 160);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 161, 'duqian', '123456', '鏉滆縼', 119, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 161);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 162, 'zouyuan', '123456', '閭规笂', 119, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 162);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 163, 'zourun', '123456', '閭规鼎', 119, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 163);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 164, 'zhugui', '123456', '鏈辫吹', 119, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 164);
-- 閮ㄩ棬120: 甯傚満鎴樼暐缁?
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 165, 'shien', '123456', '鏂芥仼', 120, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 165);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 166, 'lizhong', '123456', '鏉庡繝', 120, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 166);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 167, 'zhoutong', '123456', '鍛ㄩ€?, 120, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 167);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 168, 'tanglong', '123456', '姹ら殕', 120, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 168);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 169, 'duxing', '123456', '鏉滃叴', 120, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 169);
-- 閮ㄩ棬121-139: 鍏朵綑閮ㄩ棬锛堢畝鍖栵級
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 170, 'zhengtianshou', '123456', '閮戝ぉ瀵?, 121, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 170);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 171, 'taozongwang', '123456', '闄跺畻鏃?, 121, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 171);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 172, 'caozheng', '123456', '鏇规', 121, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 172);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 173, 'songqing', '123456', '瀹嬫竻', 121, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 173);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 174, 'gongwang', '123456', '榫氭椇', 121, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 174);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 175, 'dingdesheng', '123456', '涓佸緱鑳?, 122, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 175);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 176, 'muchun', '123456', '绌嗘槬', 122, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 176);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 177, 'xueyong', '123456', '钖涙案', 122, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 177);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 178, 'kongming', '123456', '瀛旀槑', 122, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 178);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 179, 'kongliang', '123456', '瀛斾寒', 122, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 179);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 180, 'zhangqing2', '123456', '寮犻潚', 123, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 180);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 181, 'sunerniang', '123456', '瀛欎簩濞?, 123, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 181);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 182, 'gudasao', '123456', '椤惧ぇ瀚?, 123, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 182);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 183, 'caifu', '123456', '钄＄', 123, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 183);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 184, 'baisheng', '123456', '鐧借儨', 123, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 184);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 185, 'shiqian', '123456', '鏃惰縼', 124, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 185);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 186, 'ligun', '123456', '鏉庤‘', 124, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 186);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 187, 'baoxu', '123456', '椴嶆棴', 124, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 187);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 188, 'fanrui', '123456', '妯婄憺', 124, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 188);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 189, 'xiangchong', '123456', '椤瑰厖', 124, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 189);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 190, 'malin', '123456', '椹簾', 125, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 190);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 191, 'tongwei', '123456', '绔ュ▉', 125, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 191);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 192, 'tongmeng', '123456', '绔ョ寷', 125, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 192);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 193, 'mengkuang', '123456', '瀛熷悍', 125, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 193);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 194, 'houjian', '123456', '渚仴', 125, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 194);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 195, 'chenda', '123456', '闄堣揪', 126, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 195);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 196, 'yangchun', '123456', '鏉ㄦ槬', 126, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 196);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 197, 'zhuwu', '123456', '鏈辨', 126, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 197);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 198, 'cuiping', '123456', '宕旇悕', 126, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 198);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 199, 'zhangshun2', '123456', '寮犲窛', 126, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 199);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 200, 'luqian', '123456', '闄嗚唉', 127, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 200);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 201, 'fuan', '123456', '瀵屽畨', 127, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 201);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 202, 'dongchao', '123456', '钁ｈ秴', 127, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 202);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 203, 'xueba', '123456', '钖涢湼', 127, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 203);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 204, 'gaoqiu', '123456', '楂樹繀', 127, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 204);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 205, 'caijing', '123456', '钄′含', 128, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 205);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 206, 'tongguan', '123456', '绔ヨ疮', 128, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 206);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 207, 'yangjian', '123456', '鏉ㄦ埇', 128, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 207);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 208, 'gaoyanei', '123456', '楂樿鍐?, 128, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 208);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 209, 'ximenqing', '123456', '瑗块棬搴?, 128, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 209);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 210, 'jiangzhong', '123456', '钂嬪繝', 129, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 210);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 211, 'zhangdujian', '123456', '寮犻兘鐩?, 129, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 211);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 212, 'huangwenbing', '123456', '榛勬枃鐐?, 129, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 212);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 213, 'jiaming', '123456', '璐炬皬', 129, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 213);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 214, 'ligu', '123456', '鏉庡浐', 129, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 214);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 215, 'wanglun', '123456', '鐜嬩鸡', 130, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 215);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 216, 'chaogai', '123456', '鏅佺洊', 130, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 216);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 217, 'sunxin', '123456', '瀛欐柊', 130, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 217);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 218, 'yuehe', '123456', '涔愬拰', 130, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 218);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 219, 'wangjiao', '123456', '鐜嬭繘', 130, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 219);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 220, 'luantingyu', '123456', '鏍惧环鐜?, 131, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 220);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 221, 'fangla', '123456', '鏂硅厞', 131, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 221);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 222, 'fangtianding', '123456', '鏂瑰ぉ瀹?, 131, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 222);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 223, 'wangyin', '123456', '鐜嬪瘏', 131, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 223);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 224, 'pangwanchun', '123456', '搴炰竾鏄?, 131, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 224);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 225, 'dengyuanjue', '123456', '閭撳厓瑙?, 132, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 225);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 226, 'shibao', '123456', '鐭冲疂', 132, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 226);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 227, 'lvtianduo', '123456', '鍘夊ぉ闂?, 132, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 227);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 228, 'sixingfang', '123456', '鍙歌鏂?, 132, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 228);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 229, 'baodaoyi', '123456', '鍖呴亾涔?, 132, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 229);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 230, 'zhengbiao', '123456', '閮戝姜', 133, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 230);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 231, 'gaolian', '123456', '楂樺粔', 133, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 231);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 232, 'murong', '123456', '鎱曞鐭ュ簻', 133, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 232);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 233, 'liangzhongshu', '123456', '姊佷腑涔?, 133, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 233);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 234, 'caizhifu', '123456', '钄＄煡搴?, 133, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 234);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 235, 'chengwanli', '123456', '绋嬩竾閲?, 134, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 235);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 236, 'liushimeng', '123456', '鍒樹笘鐩?, 134, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 236);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 237, 'wenrenda', '123456', '闂讳汉杈?, 134, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 237);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 238, 'wangzheng', '123456', '鐜嬫', 134, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 238);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 239, 'liuzan', '123456', '鍒樿禐', 134, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 239);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 240, 'wudalang', '123456', '姝﹀ぇ閮?, 135, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 240);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 241, 'panjinlian', '123456', '娼橀噾鑾?, 135, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 241);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 242, 'wangpo', '123456', '鐜嬪﹩', 135, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 242);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 243, 'yanqinxi', '123456', '闃庡﹩鎯?, 135, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 243);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 244, 'tangniuer', '123456', '鍞愮墰鍎?, 135, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 244);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 245, 'niuer', '123456', '鐗涗簩', 136, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 245);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 246, 'zhangjiaotou', '123456', '寮犳暀澶?, 136, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 246);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 247, 'jiner', '123456', '閿﹀効', 136, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 247);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 248, 'yingguan', '123456', '杩庡効', 136, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 248);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 249, 'meixiang', '123456', '姊呴', 136, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 249);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 250, 'chunxiang', '123456', '鏄ラ', 137, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 250);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 251, 'liniangzi', '123456', '鏋楀瀛?, 137, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 251);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 252, 'songtaigong', '123456', '瀹嬪お鍏?, 137, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 252);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 253, 'litaigong', '123456', '鏉庡お鍏?, 137, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 253);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 254, 'kongtaigong', '123456', '瀛斿お鍏?, 137, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 254);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 255, 'shitaigong', '123456', '鍙插お鍏?, 138, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 255);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 256, 'songpo', '123456', '瀹嬪﹩', 138, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 256);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 257, 'yanpo', '123456', '闃庡﹩', 138, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 257);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 258, 'panlaopo', '123456', '娼樿€佸﹩', 138, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 258);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 259, 'lilaopo', '123456', '鏉庤€佸﹩', 138, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 259);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 260, 'zhongsan', '123456', '寮犱笁', 139, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 260);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 261, 'lisi', '123456', '鏉庡洓', 139, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 261);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 262, 'wangwu', '123456', '鐜嬩簲', 139, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 262);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 263, 'zhaoliu', '123456', '璧靛叚', 139, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 263);
INSERT INTO sys_user (id, username, password, real_name, dept_id, status, security_level, create_time, update_time) SELECT 264, 'sunqi', '123456', '瀛欎竷', 139, 1, 1, datetime('now'), datetime('now') WHERE NOT EXISTS (SELECT 1 FROM sys_user WHERE id = 264);

-- ==================== 鐢ㄦ埛鍏艰亴璁板綍 (涓婚儴闂? ====================
INSERT INTO sys_user_post (user_id, dept_id, post_id, is_main)
SELECT u.id, u.dept_id, 0, 1 FROM sys_user u WHERE u.id BETWEEN 100 AND 264
AND NOT EXISTS (SELECT 1 FROM sys_user_post WHERE user_id = u.id AND is_main = 1);
